---
- name: Remove packages
  ansible.builtin.apt:
    pkg:
      - apache
      - puppet
      - mysql-common
      - mysql-server
      - mysql-client
      - exim4
    state: absent

- name: Installing common packages...be patient!
  ansible.builtin.apt:
    pkg:
      - apticron
      - bzip2
      - curl
      - git
      - vim
      - neovim
      - htop
      - wget
      - apache2-utils
      - php-fpm
      - rkhunter
      - tar
      - zip
      - unzip
      - nginx-full
      - mariadb-common
      - mariadb-server
      - mariadb-client
      - wireguard
    state: present
    update_cache: yes
