---
- name: Check if /etc/cloud/cloud.cfg exists
  ansible.builtin.stat:
    path: /etc/cloud/cloud.cfg
  register: stat_result

# Allows hostname to be altered by the next task
- name: Set cloud init preserve_hostname
  ansible.builtin.lineinfile:
    path: /etc/cloud/cloud.cfg
    regexp: "^preserve_hostname: false$"
    line: "preserve_hostname: true"
  when: stat_result.stat.exists

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
    use: debian

- name: Write hostname and FQDN to /etc/hosts via template
  ansible.builtin.template:
    src: etc_hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0064
