---
# Change config
- name: Tweak nginx configuration
  ansible.builtin.lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^worker_processes auto;"
      line: "worker_processes {{ ansible_processor_vcpus | default(ansible_processor_count) }};"
    - regexp: "	worker_connections 768;"
      line: "	worker_connections 1024;"
    - regexp: "^	# server_tokens off;"
      line: "	server_tokens off;\n	client_max_body_size 64m;"
    - regexp: "^	error_log /var/log/nginx/error.log;"
      line: "	error_log /var/log/nginx/error.log warn;"
    - regexp: "^	access_log /var/log/nginx/access.log;"
      line: "	access_log /var/log/nginx/other_vhosts_access.log;"
#
# validate the tweaked config file
- name: Validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: False
  notify:
    - restart nginx
