---
# 3600 seconds is 1 hour
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - update

- name: Upgrade the installed packages
  ansible.builtin.apt:
    upgrade: dist
  tags:
    - update
