---
- name: Install unattended-upgrades package
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present

- name: Copy APT periodic config
  ansible.builtin.template:
    src: etc-apt-apt.conf.d-10periodic.j2
    dest: /etc/apt/apt.conf.d/10periodic
    owner: root
    group: root
    mode: 644
  notify:
    - restart cron

- name: Copy unattended upgrades config
  ansible.builtin.template:
    src: etc-apt-apt.conf.d-50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 644
  notify:
    - restart cron
