---
# This file is for variables which apply to all hosts

# Users & their SSH public keys
users:
  - name: alice
    passwd: PASSWORD_HASH_HERE_SEE_DOCS
    comment: "Alice Momod"
    uid: 2000
    shell: /usr/bin/zsh
    groups:
      - sudo
      - adm
      - www-data
    append: yes

keys:
  - user: alice
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

# systemd-timesyncd config
timezone: "Europe/London"

# Use python3 on managed hosts
ansible_python_interpreter: /usr/bin/python3

# PowerDNS Caching nameserver (pdns-recursor)
pdns_rec_config:
  allow-from:
    - "127.0.0.0/8"
    - "10.0.0.0/8"
    - "192.168.0.0/16"
    - "172.16.0.0/12"
    - "::1/128"
    - "fe80::/10"
  local-address: "{{ ansible_default_ipv4['address'] }}:53"
