---
# Notes
# 2vcpu, 4GB RAM, 40GB Disk Local

public_ip: 00.00.00.00
public_ipv6: "0000:0000:0000:0000::1"
hostname: server
fqdn: server.example.com

# Remote user to use when running play-setup
# This is usually root or ubuntu depending on host provider
# NOTE after play-setup has run niether root nor ubuntu have access
# To rerun setup change this to the same user as ansible_user below
setup_ansible_user: "root"

# normal ansible user is yourself
ansible_user: your_user_name
# use your own ssh keys by default
ansible_ssh_private_key_file: "~/.ssh/id_rsa"

## Role vars
## DEFAULTS are listed but commented out if unchanged! ##

# Define which users are allowed to access ssh, space separated
ssh_allowed_users: "alice "

## geerlingguy.firewall
#firewall_state: started
#firewall_enabled_at_boot: true

#firewall_flush_rules_and_chains: true

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "443"
#firewall_allowed_udp_ports: []
#firewall_forwarded_tcp_ports: []
#firewall_forwarded_udp_ports: []
#firewall_additional_rules: []
#firewall_enable_ipv6: true
#firewall_ip6_additional_rules: []
#firewall_log_dropped_packets: true

# Set to true to ensure other firewall management software is disabled.
firewall_disable_firewalld: true
firewall_disable_ufw: true
## End geerlingguy.firewall

## Fail2ban
# ignoreip list should be space separated
#fail2ban_ignoreip:
fail2ban_bantime: 1200
#fail2ban_maxretry: 3
#fail2ban_destemail: root@localhost

#fail2ban_postfix_enabled: false
#fail2ban_nginx_http_auth_enabled: true
#fail2ban_nginx_botsearch_enabled: true
