---
# Notes
# 2vcpu, 4GB RAM, 40GB Disk Local

public_ip: 00.00.00.00
public_ipv6: "0000:0000:0000:0000::1"
hostname: server
fqdn: server.example.com

# Remote user to use when running play-setup
# This is usually root or ubuntu depending on host provider
# NOTE after play-setup has run niether root nor ubuntu have access
# To rerun setup change this to the same user as ansible_user below
setup_ansible_user: "root"

# normal ansible user is yourself
ansible_user: your_user_name
# use your own ssh keys by default
ansible_ssh_private_key_file: "~/.ssh/id_rsa"

## Role vars
## DEFAULTS are listed but commented out if unchanged! ##

# Define which users are allowed to access ssh, space separated
ssh_allowed_users: "alice "

## Fail2ban
# ignoreip list should be space separated
#fail2ban_ignoreip:
fail2ban_bantime: 1200
#fail2ban_maxretry: 3
#fail2ban_destemail: root@localhost

#fail2ban_postfix_enabled: false
#fail2ban_nginx_http_auth_enabled: true
#fail2ban_nginx_botsearch_enabled: true

## Certbot-dns-gandi
letsencrypt_registered_email:

## Postfix
#postfix_myhostname: "{{ fqdn }}"
#postfix_mynetworks: "127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128"
#postfix_relayhost: ""
postfix_inet_interfaces: all
#postfix_inet_protocols: all
postfix_mydestination: "localhost, localhost.{{ fqdn }}, {{ fqdn }}"
postfix_email_recipient: "root@{{ fqdn }}"
# 'all' or 'local'
postfix_catch: local
