---
# Include tasks for essential applications
- name: Check if haproxy is enabled
  set_fact:
    haproxy_enabled: true
  loop: "{{ lookup('list', enabled_services) }}"
  when: "'haproxy' in item"

- name: Add haproxy pod
  include_tasks: applications/haproxy.yml
  when: haproxy_enabled|default(false) == true


# Include tasks for Admin applications
- name: Check if Grafana is enabled
  set_fact:
    grafana_enabled: true
  loop: "{{ lookup('list', enabled_services) }}"
  when: "'grafana' in item"

- name: Add Grafana pod
  include_tasks: applications/grafana.yml
  when: grafana_enabled|default(false) == true


# Include tasks for enabled applications
- name: Check if Miniflux is enabled
  set_fact:
    miniflux_enabled: true
  loop: "{{ lookup('list', enabled_services) }}"
  when: "'miniflux' in item"

- name: Add Miniflux feed reader pod
  include_tasks: applications/miniflux.yml
  when: miniflux_enabled|default(false) == true
#
#
#
#
#
# TODO migrate to ansible podman
# - name: Check if kanboard is enabled
#   set_fact:
#     kanboard_enabled: true
#   loop: "{{ lookup('list', enabled_services) }}"
#   when: "'kanboard' in item"

# - blockinfile:
#     path: "/opt/docker_services/docker-compose.yml"
#     block: "{{ lookup('template', 'templates/kanboard.yml.j2') }}"
#     marker: "#{mark} ANSIBLE MANAGED BLOCK FOR: kanboard"
#   when: kanboard_enabled == true

# - name: Check if vikunja is enabled
#   set_fact:
#     vikunja_enabled: true
#   loop: "{{ lookup('list', enabled_services) }}"
#   when: "'vikunja' in item"

# - blockinfile:
#     path: "/opt/docker_services/docker-compose.yml"
#     block: "{{ lookup('template', 'templates/vikunja.yml.j2') }}"
#     marker: "#{mark} ANSIBLE MANAGED BLOCK FOR: vikunja"
#   when: vikunja_enabled == true

# - name: Check if radicale is enabled
#   set_fact:
#     radicale_enabled: true
#   loop: "{{ lookup('list', enabled_services) }}"
#   when: "'radicale' in item"

# - blockinfile:
#     path: "/opt/docker_services/docker-compose.yml"
#     block: "{{ lookup('template', 'templates/radicale.yml.j2') }}"
#     marker: "#{mark} ANSIBLE MANAGED BLOCK FOR: radicale"
#   when: radicale_enabled == true

# - name: Check if Wallabag is enabled
#   set_fact:
#     wallabag_enabled: true
#   loop: "{{ lookup('list', enabled_services) }}"
#   when: "'wallabag' in item"

# - blockinfile:
#     path: "/opt/docker_services/docker-compose.yml"
#     block: "{{ lookup('template', 'templates/wallabag.yml.j2') }}"
#     marker: "#{mark} ANSIBLE MANAGED BLOCK FOR: wallabag"
#   when: wallabag_enabled == true

