---
# 'Wireguard' role installs the Wireguard tools package and
# pre-generates server side keys.
# This role puts configuration into place and starts Wireguard on the server

- name: Register server Wireguard private key
  ansible.builtin.slurp:
    src: /etc/wireguard/privatekey
  register: server_wg_private_key
  become: yes

- name: Register the client Wireguard public key
  ansible.builtin.slurp:
    src: ../../local/files/wireguard/client-publickey
  delegate_to: localhost
  register: client_wg_public_key
  become: no

- name: Deploy systemd .netdev for momod0 network
  ansible.builtin.template:
    src: 50-momod0.netdev.j2
    dest: /etc/systemd/network/50-momod0.netdev
    owner: root
    group: systemd-network
    mode: 0640
  become: yes

- name: Deploy systemd .network for momod0 network
  ansible.builtin.template:
    src: 52-momod0.network.j2
    dest: /etc/systemd/network/52-momod0.network
    owner: root
    group: systemd-network
    mode: 0640
  become: yes

- name: Deploy systemd .netdev for momod1 network
  ansible.builtin.template:
    src: 54-momod1.netdev.j2
    dest: /etc/systemd/network/54-momod1.netdev
    owner: root
    group: systemd-network
    mode: 0640
  become: yes

- name: Deploy systemd .network for momod1 network
  ansible.builtin.template:
    src: 56-momod1.network.j2
    dest: /etc/systemd/network/56-momod1.network
    owner: root
    group: systemd-network
    mode: 0640
  become: yes

- name: Reread systemd configs
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted
