---
- hosts: all
  become: yes
  roles:
    - hostname
    - apt
    - unattended-upgrades
    - sshd
    - common-packages
    - nginx-config
    - geerlingguy.firewall
    - sysctl
    - powerdns.pdns_recursor
    - fail2ban
    - certbot-dns-gandi
    - postfix-send-only
    - podman
    - wireguard

- hosts: dev
  become: yes

- hosts: prod
  become: yes
