---
- hosts: all
  become: yes
  roles:
    - hostname
    - apt
    - unattended-upgrades
    - geerlingguy.ntp
    - sshd
    - common-packages
    - nginx-config
    - geerlingguy.firewall
    - powerdns.pdns_recursor

- hosts: dev
  become: yes

- hosts: prod
  become: yes
