---
- hosts: all
  become: yes
  roles:
    - hostname
    - apt
    - unattended-upgrades
    - sshd
    - common-packages
    - nginx-config
    - sysctl
    - fail2ban
    - certbot-dns-gandi
    - postfix-send-only
    - wireguard
    - podman

- hosts: dev
  become: yes

- hosts: prod
  become: yes
