---
- hosts: all
  become: yes
  roles:
    - hostname
    - apt
    - unattended-upgrades
    - geerlingguy.ntp
    - sshd
    - common-packages
    - geerlingguy.firewall

- hosts: dev
  become: yes

- hosts: prod
  become: yes
