---
- name: Set sysctl values for Wireguard
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: yes
    reload: yes
  with_items:
    - { name: "net.ipv4.ip_forward", value: "1" }
    - { name: "net.ipv6.conf.default.forwarding", value: "1" }
    - { name: "net.ipv6.conf.all.forwarding", value: "1" }
