---
enabled_services:
  - haproxy
#- miniflux
#- kanboard
#- wallabag
#- radicale
#- vikunja
#- grafana


# Which user owns the container data in bind mounts
app_services_user: "root"

###

# Database root password for all services
mariadb_root_password:

# Kanboard password
kanboard_db_password:
vikunja_db_password:

# Encrypted user account passwords (for application email)
# Advice on generating
# https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-generate-encrypted-passwords-for-the-user-module
kanboard_email_passwd_crypt:
vikunja_email_passwd_crypt:
vikunja_email_password:

radicale_users:

# Wallabag
wallabag_db_password:
wallabag_mail_host:
wallabag_mail_user:
wallabag_email_passwd_crypt:
wallabag_mail_from:
wallabag_secret:

# Miniflux
miniflux_admin_user:
miniflux_admin_password:
miniflux_postgres_password:

######

# Might need to change, kept here to avoid collisions when
# adding new services
podhaproxy_subuid_base: 1000000
miniflux_subuid_base: 1065536
radicale_subuid_base: 1131072
kanboard_subuid_base: 1196608
vikunja_subuid_base: 1262144
wallabag_subuid_base: 1327680
# Increment by 65536 for a new entry

# Should not need to be changed, kept hear to avoid collisions
# when creating new services
podhaproxy_user_uid: 6000
miniflux_user_uid: 6001
radicale_user_uid: 6002
kanboard_user_uid: 6003
vikunja_user_uid: 6004
wallabag_user_uid: 6005
# Increment by 1
