---
# Use podman secret to store db user/password?

- name: Copy pod-haproxy systemd unit file into place
  ansible.builtin.copy:
    src: files/pod-haproxy.service
    dest: /etc/systemd/system/pod-haproxy.service
    owner: root
    group: root
    mode: 0644
# TODO register if this has changed

- name: Copy haproxy app systemd unit file into place
  ansible.builtin.template:
    src: templates/container-haproxy.service.j2
    dest: /etc/systemd/system/container-haproxy.service
    owner: root
    group: root
    mode: 0644
# TODO register if this has changed

- name: Reread systemd configs
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true
# TODO read register and only do this if service file has changed

- name: Enable & start haproxy pod container
  ansible.builtin.systemd:
    name: pod-haproxy
    state: restarted
    enabled: yes
  become: true
# TODO read register and only restart if service file has changed

- name: Enable & start haproxy app container
  ansible.builtin.systemd:
    name: container-haproxy
    state: restarted
    enabled: yes
  become: true
# TODO read register and only restart if service file has changed
