---
- name: Create directory for Miniflux database
  ansible.builtin.file:
    path: /data/momod/miniflux-postgres/12
    state: directory
    owner: "{{ app_services_user }}"
    group: "{{ app_services_user }}"
    mode: 0755

- name: Add a pod for miniflux
  containers.podman.podman_pod:
    name: miniflux
    state: started
    ports:
      - 8080:8080

# Add containers to pod
- name: Add miniflux-postgres container
  containers.podman.podman_container:
    name: miniflux-postgres
    image: docker.io/library/postgres:12
    state: present
    recreate: yes
    restart_policy: on-failure:5
    env:
      POSTGRES_USER: "miniflux"
      POSTGRES_PASSWORD: "{{ miniflux_postgres_password }}"
    volume: /data/momod/miniflux-postgres/12:/var/lib/postgresql/data
    pod: miniflux

- name: Add miniflux container
  containers.podman.podman_container:
    name: miniflux-app
    image: docker.io/miniflux/miniflux:latest
    state: present
    recreate: yes
    restart_policy: on-failure:5
    env:
      BASE_URL: "https://{{ apps_domain }}/"
      DATABASE_URL: "postgres://miniflux:{{ miniflux_postgres_password }}@miniflux-postgres/miniflux?sslmode=disable"
      RUN_MIGRATIONS: 1
      CREATE_ADMIN: 1
      ADMIN_USERNAME: "{{ miniflux_admin_user }}"
      ADMIN_PASSWORD: "{{ miniflux_admin_password }}"
    expose:
      - 8080
    pod: miniflux
#
# Add systemd service?
