---
- name: Add System user to run Miniflux with
  ansible.builtin.user:
    name: miniflux
    uid: "{{ miniflux_user_uid }}"
    password: "*"
    state: present
    system: yes

- name: Check linger is enabled for miniflux user
  ansible.builtin.stat:
    path: "/var/lib/systemd/linger/miniflux"
  register: miniflux_linger

- name: Enable-linger for miniflux
  ansible.builtin.command: "loginctl enable-linger miniflux"
  when: not miniflux_linger.stat.exists

# ensure XDG_RUNTIME_DIR is set for miniflux user?
# Can specify as environment
# export XDG_RUNTIME_DIR=/run/user/"{{ miniflux_user_uid }}"

# Use podman secret to store db user/password?

- name: Create directory for Miniflux database
  ansible.builtin.file:
    path: /data/momod/miniflux-postgres/12
    state: directory
    owner: miniflux
    group: miniflux
    mode: 0755
#
#
# Add systemd files.

# Enable service
# become: true
#  become_user: miniflux
#  environment:
#    XDG_RUNTIME_DIR: /run/user/"{{ miniflux_user_uid }}"
# Start service

