---
- name: Installing Wireguard package
  ansible.builtin.apt:
    pkg:
      - wireguard
    state: present
    update_cache: yes

- name: Generate Wireguard private key
  ansible.builtin.shell: umask 077; wg genkey > /etc/wireguard/privatekey
  args:
    creates: /etc/wireguard/privatekey
  become: yes

- name: Generate Wireguard public key
  ansible.builtin.shell: umask 077; wg pubkey < /etc/wireguard/privatekey > /etc/wireguard/publickey
  args:
    creates: /etc/wireguard/publickey
  become: yes

- name: Backup the server Wireguard private key to momod/local/fetched
  ansible.builtin.fetch:
    src: /etc/wireguard/privatekey
    dest: ../../local/fetched

- name: Backup the server public Wireguard key to momod/local/fetched
  ansible.builtin.fetch:
    src: /etc/wireguard/publickey
    dest: ../../local/fetched
