---
# 'Wireguard' package (contains tools) is installed in the
# common-packages role

- name: Generate Wireguard private key
  ansible.builtin.shell: umask 077; wg genkey > /etc/wireguard/privatekey
  args:
    creates: /etc/wireguard/privatekey
  become: yes

- name: Generate Wireguard public key
  ansible.builtin.shell: umask 077; wg pubkey < /etc/wireguard/privatekey > /etc/wireguard/publickey
  args:
    creates: /etc/wireguard/publickey
  become: yes

- name: Backup the private key to your momod/local/fetched directory
  ansible.builtin.fetch:
    src: /etc/wireguard/privatekey
    dest: ../../local/fetched

- name: Backup the public key to your momod/local/fetched directory
  ansible.builtin.fetch:
    src: /etc/wireguard/publickey
    dest: ../../local/fetched

- name: Register server private key
  ansible.builtin.slurp:
    src: /etc/wireguard/privatekey
  register: server_wg_private_key
  become: yes

- name: Copy Wireguard config file to server
  ansible.builtin.template:
    src: momod0.conf.j2
    dest: /etc/wireguard/momod0.conf
    owner: root
    group: root
    mode: 0600
  become: yes
#
# enable service with wg-quick
# start serviec with wg-quick
# check connection?

#
# Our local public key is needed?
# Document manually copying to the momod/local folder
# Have task check it exists
#
