---
- name: Make sure OpenDKIM and dependencies are installed
  ansible.builtin.apt:
    pkg:
      - opendkim
      - opendkim-tools

- name: Make sure the OpenDKIM config directory is present
  ansible.builtin.file:
    state: directory
    path: /etc/opendkim
    group: opendkim
    owner: opendkim
    mode: 0644

- name: Make sure the OpenDKIM key directories are present
  ansible.builtin.file:
    state: directory
    path: /etc/dkimkeys
    group: opendkim
    owner: opendkim
    mode: 0700

- name: Generate OpenDKIM keys
  ansible.builtin.command:
    cmd: opendkim-genkey -r -d {{ fqdn }} -D /etc/dkimkeys/
    creates: /etc/dkimkeys/default.private

- name: Copy default opendkim config into place
  ansible.builtin.copy:
    src: default_opendkim.j2
    dest: /etc/default/opendkim
    owner: root
    group: root
    mode: 0644

- name: Copy opendkim.conf into place
  ansible.builtin.template:
    src: opendkim.conf.j2
    dest: /etc/opendkim.conf
    owner: opendkim
    group: opendkim
    mode: 0644
  notify:
    - restart opendkim
    - restart postfix

- name: Download default.txt for DKIM DNS TXT records to 'local/fetched/'
  ansible.builtin.fetch:
    src: /etc/dkimkeys/default.txt
    dest: ../../local/fetched
